ci:
    autofix_prs: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-yaml
      - id: check-merge-conflict
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args: ['--skip', '*.ipynb']
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.12.0.3
    hooks:
      - id: hadolint
        args: [
          --ignore, DL3025,
          --ignore, DL3018,
          --ignore, DL3008,
          --ignore, DL3003,
          --ignore, DL3013,
          --ignore, SC1091,
        ]
        files: ^Dockerfile
  - repo: 'https://github.com/astral-sh/ruff-pre-commit'
    rev: v0.2.2
    hooks:
      - id: ruff
        args:
          - '--fix'
          - '--exit-non-zero-on-fix'
      - id: ruff-format
